package grammars

import (
	"fmt"
	"slices"
	"strings"

	"github.com/spf13/cast"

	contractsdatabase "github.com/dracory/neat/contracts/database"
	"github.com/dracory/neat/contracts/database/schema"
)

type Oracle struct {
	attributeCommands []string
	modifiers         []func(schema.Blueprint, schema.ColumnDefinition) string
	serials           []string
	wrap              *Wrap
}

func NewOracle(tablePrefix string) *Oracle {
	oracle := &Oracle{
		attributeCommands: []string{},
		serials:           []string{"bigInteger", "integer", "mediumInteger", "smallInteger", "tinyInteger"},
		wrap:              NewWrap(contractsdatabase.DriverOracle, tablePrefix),
	}
	oracle.modifiers = []func(schema.Blueprint, schema.ColumnDefinition) string{
		// The sort should not be changed, it effects the SQL output
		// Oracle requires DEFAULT before NULL/NOT NULL
		oracle.ModifyUnsigned,
		oracle.ModifyCollation,
		oracle.ModifyDefault,
		oracle.ModifyNullable,
		oracle.ModifyOnUpdate,
		oracle.ModifyIncrement,
		oracle.ModifyComment,
		oracle.ModifyAfter,
		oracle.ModifyFirst,
	}

	return oracle
}

func (r *Oracle) CompileAdd(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	column, err := r.getColumn(blueprint, command.Column)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("alter table %s add %s", table, column), nil
}

func (r *Oracle) CompileChange(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	column, err := r.getColumn(blueprint, command.Column)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("alter table %s modify %s", table, column), nil
}

func (r *Oracle) CompileColumns(schema, table string) string {
	// Use user_tab_columns instead of all_tab_columns to avoid needing owner parameter
	// user_tab_columns automatically uses the current user's schema
	// Note: comments are not in user_tab_columns, they're in user_col_comments
	// Join with user_tab_identity_cols to detect identity columns
	return fmt.Sprintf(
		"SELECT c.column_name AS name, c.data_type AS type_name, c.char_length AS length, c.nullable, c.data_default AS \"default\", "+
			"CASE WHEN i.column_name IS NOT NULL THEN 1 ELSE 0 END AS autoincrement "+
			"FROM user_tab_columns c LEFT JOIN user_tab_identity_cols i ON c.table_name = i.table_name AND c.column_name = i.column_name "+
			"WHERE c.table_name = '%s'",
		strings.ToUpper(table))
}

func (r *Oracle) CompileComment(_ schema.Blueprint, _ *schema.Command) (string, error) {
	return "", nil
}

func (r *Oracle) CompileCreate(blueprint schema.Blueprint) (string, error) {
	columns, err := r.getColumns(blueprint)
	if err != nil {
		return "", err
	}
	primaryCommand := getCommandByName(blueprint.GetCommands(), "primary")
	if primaryCommand != nil {
		// Check if the primary key is on a single identity column
		// If so, add it inline to avoid Oracle syntax issues
		if len(primaryCommand.Columns) == 1 {
			for i, col := range columns {
				// Check if this column is the primary key column and has identity
				if strings.Contains(col, "generated by default as identity") {
					for _, pkCol := range primaryCommand.Columns {
						quotedPkCol, err := r.wrap.Column(pkCol)
						if err != nil {
							return "", err
						}
						if strings.HasPrefix(col, quotedPkCol+" ") {
							// Add PRIMARY KEY inline
							columns[i] = col + " primary key"
							primaryCommand.ShouldBeSkipped = true
							goto done
						}
					}
				}
			}
		}
		// If not handled inline, add as separate constraint
		if !primaryCommand.ShouldBeSkipped {
			columnized, err := r.wrap.Columnize(primaryCommand.Columns)
			if err != nil {
				return "", err
			}
			columns = append(columns, fmt.Sprintf("primary key (%s)", columnized))
			primaryCommand.ShouldBeSkipped = true
		}
	}

done:
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("create table %s (%s)", table, strings.Join(columns, ", ")), nil
}

func (r *Oracle) CompileDisableForeignKeyConstraints() string {
	return ""
}

func (r *Oracle) CompileDrop(blueprint schema.Blueprint) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("drop table %s cascade constraints", table), nil
}

func (r *Oracle) CompileDropAllDomains(_ []string) (string, error) {
	return "", nil
}

func (r *Oracle) CompileDropAllTables(tables []string) (string, error) {
	var statements []string
	for _, table := range tables {
		quotedTable, err := r.wrap.Table(table)
		if err != nil {
			return "", err
		}
		statements = append(statements, fmt.Sprintf("drop table %s cascade constraints", quotedTable))
	}
	return strings.Join(statements, "; "), nil
}

func (r *Oracle) CompileDropAllTypes(_ []string) (string, error) {
	return "", nil
}

func (r *Oracle) CompileDropAllViews(views []string) (string, error) {
	var statements []string
	for _, view := range views {
		quotedView, err := r.wrap.Table(view)
		if err != nil {
			return "", err
		}
		statements = append(statements, fmt.Sprintf("drop view %s", quotedView))
	}
	return strings.Join(statements, "; "), nil
}

func (r *Oracle) CompileDropColumn(blueprint schema.Blueprint, command *schema.Command) ([]string, error) {
	columns, err := r.wrap.Columns(command.Columns)
	if err != nil {
		return nil, err
	}

	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return nil, err
	}

	var statements []string
	for _, column := range columns {
		statements = append(statements, fmt.Sprintf("alter table %s drop column %s", table, column))
	}

	return statements, nil
}

func (r *Oracle) CompileDropForeign(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	column, err := r.wrap.Column(command.Index)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("alter table %s drop constraint %s", table, column), nil
}

func (r *Oracle) CompileDropFullText(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	return r.CompileDropIndex(blueprint, command)
}

func (r *Oracle) CompileDropIfExists(blueprint schema.Blueprint) (string, error) {
	tableName := strings.ToUpper(blueprint.GetTableName())
	// Use the same pattern as helper.go for consistency
	// Simple PL/SQL block with exception handling
	// Add trailing semicolon for proper execution
	return fmt.Sprintf("BEGIN EXECUTE IMMEDIATE 'DROP TABLE %s CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;", tableName) + ";", nil
}

func (r *Oracle) CompileDropIndex(_ schema.Blueprint, command *schema.Command) (string, error) {
	column, err := r.wrap.Column(command.Index)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("drop index %s", column), nil
}

func (r *Oracle) CompileDropPrimary(blueprint schema.Blueprint, _ *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("alter table %s drop primary key cascade", table), nil
}

func (r *Oracle) CompileDropUnique(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	return r.CompileDropIndex(blueprint, command)
}

func (r *Oracle) CompileEnableForeignKeyConstraints() string {
	return ""
}

func (r *Oracle) CompileForeign(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	index, err := r.wrap.Column(command.Index)
	if err != nil {
		return "", err
	}
	columns, err := r.wrap.Columnize(command.Columns)
	if err != nil {
		return "", err
	}
	on, err := r.wrap.Table(command.On)
	if err != nil {
		return "", err
	}
	references, err := r.wrap.Columnize(command.References)
	if err != nil {
		return "", err
	}

	sql := fmt.Sprintf("alter table %s add constraint %s foreign key (%s) references %s (%s)",
		table, index, columns, on, references)
	// Oracle doesn't support ON UPDATE for foreign keys, only ON DELETE
	if command.OnDelete != "" && r.wrap.IsValidAction(command.OnDelete) {
		sql += " on delete " + command.OnDelete
	}

	return sql, nil
}

func (r *Oracle) CompileForeignKeys(schema, table string) string {
	// Use user_cons_columns instead of all_cons_columns to avoid needing owner parameter
	// user_cons_columns automatically uses the current user's schema
	// Oracle doesn't support ON UPDATE for foreign keys, so we only query delete_rule
	return fmt.Sprintf(
		`SELECT 
			c.constraint_name AS name, 
			LISTAGG(c.column_name, ',') WITHIN GROUP (ORDER BY c.position) AS columns, 
			'' AS foreign_schema, 
			r.table_name AS foreign_table, 
			LISTAGG(r.column_name, ',') WITHIN GROUP (ORDER BY r.position) AS foreign_columns, 
			con.delete_rule AS on_delete, 
			'' AS on_update 
		FROM user_cons_columns c
		JOIN user_constraints con ON c.constraint_name = con.constraint_name
		JOIN user_cons_columns r ON con.r_constraint_name = r.constraint_name
		WHERE c.table_name = upper('%s') 
			AND con.constraint_type = 'R'
		GROUP BY c.constraint_name, r.table_name, con.delete_rule`,
		table,
	)
}

func (r *Oracle) CompileFullText(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	return r.compileKey(blueprint, command, "index")
}

func (r *Oracle) CompileIndex(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	index, err := r.wrap.Column(command.Index)
	if err != nil {
		return "", err
	}
	columns, err := r.wrap.Columnize(command.Columns)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("create index %s on %s(%s)", index, table, columns), nil
}

func (r *Oracle) CompileIndexes(schema, table string) string {
	// Use user_ind_columns instead of all_ind_columns to avoid needing table_owner
	// Join with user_constraints to identify primary key indexes
	return fmt.Sprintf(
		"select ic.index_name as name, listagg(ic.column_name, ',') within group (order by ic.column_position) as columns, "+
			"i.uniqueness as type, "+
			"case when c.constraint_type = 'P' then 1 else 0 end as primary "+
			"from user_ind_columns ic "+
			"join user_indexes i on ic.index_name = i.index_name "+
			"left join user_constraints c on ic.index_name = c.index_name and c.constraint_type = 'P' "+
			"where ic.table_name = upper('%s') "+
			"group by ic.index_name, i.uniqueness, c.constraint_type",
		table,
	)
}

func (r *Oracle) CompilePrimary(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	columns, err := r.wrap.Columnize(command.Columns)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("alter table %s add primary key (%s)", table, columns), nil
}

func (r *Oracle) CompileRename(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	to, err := r.wrap.Table(command.To)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("alter table %s rename to %s", table, to), nil
}

func (r *Oracle) CompileRenameColumn(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	from, err := r.wrap.Column(command.From)
	if err != nil {
		return "", err
	}
	to, err := r.wrap.Column(command.To)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("alter table %s rename column %s to %s", table, from, to), nil
}

func (r *Oracle) CompileRenameIndex(_ schema.Schema, _ schema.Blueprint, command *schema.Command) ([]string, error) {
	from, err := r.wrap.Column(command.From)
	if err != nil {
		return nil, err
	}
	to, err := r.wrap.Column(command.To)
	if err != nil {
		return nil, err
	}
	return []string{
		fmt.Sprintf("alter index %s rename to %s", from, to),
	}, nil
}

func (r *Oracle) CompileTables(database string) string {
	// Use user_tables instead of all_tables to automatically query current user's tables
	// This avoids needing to specify the owner parameter
	return "select table_name as name from user_tables order by table_name"
}

func (r *Oracle) CompileTypes() string {
	return ""
}

func (r *Oracle) CompileUnique(blueprint schema.Blueprint, command *schema.Command) (string, error) {
	return r.compileKey(blueprint, command, "unique")
}

func (r *Oracle) CompileViews(database string) string {
	return fmt.Sprintf("select view_name as name, text as definition from all_views where owner = upper(%s) order by view_name", r.wrap.Quote(database))
}

func (r *Oracle) GetAttributeCommands() []string {
	return r.attributeCommands
}

func (r *Oracle) ModifyAfter(_ schema.Blueprint, column schema.ColumnDefinition) string {
	if after := column.GetAfter(); after != "" {
		return " after " + after
	}

	return ""
}

func (r *Oracle) ModifyCollation(_ schema.Blueprint, column schema.ColumnDefinition) string {
	// Oracle doesn't support collation in column definitions
	return ""
}

func (r *Oracle) ModifyComment(_ schema.Blueprint, _ schema.ColumnDefinition) string {
	// Oracle doesn't support inline comments in CREATE TABLE statements
	// Comments are added separately using COMMENT ON COLUMN syntax
	return ""
}

func (r *Oracle) ModifyDefault(_ schema.Blueprint, column schema.ColumnDefinition) string {
	if column.GetDefault() != nil {
		def := column.GetDefault()
		// Oracle doesn't allow quoted numbers or booleans as defaults
		// Only quote strings and expressions
		switch value := def.(type) {
		case bool:
			return fmt.Sprintf(" default %d", cast.ToInt(value))
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return fmt.Sprintf(" default %v", value)
		case Expression:
			return fmt.Sprintf(" default %s", string(value))
		default:
			return fmt.Sprintf(" default %s", getDefaultValue(def))
		}
	}

	return ""
}

func (r *Oracle) ModifyFirst(_ schema.Blueprint, column schema.ColumnDefinition) string {
	// Oracle doesn't support FIRST in column definitions
	return ""
}

func (r *Oracle) ModifyIncrement(_ schema.Blueprint, column schema.ColumnDefinition) string {
	if slices.Contains(r.serials, column.GetType()) && column.GetAutoIncrement() {
		return " generated by default as identity"
	}

	return ""
}

func (r *Oracle) ModifyOnUpdate(_ schema.Blueprint, column schema.ColumnDefinition) string {
	// Oracle doesn't support ON UPDATE in column definitions
	return ""
}

func (r *Oracle) ModifyNullable(_ schema.Blueprint, column schema.ColumnDefinition) string {
	// Skip NOT NULL for auto-increment columns since GENERATED BY DEFAULT AS IDENTITY
	// automatically makes the column NOT NULL in Oracle
	if !column.GetNullable() && column.GetAutoIncrement() {
		return ""
	}
	// For Change operations, skip NOT NULL modification to avoid ORA-01442
	// This is a limitation of Oracle's ALTER TABLE MODIFY syntax
	// The column's nullability should be set correctly during CREATE
	if column.GetChange() {
		return ""
	}
	if column.GetNullable() {
		return " null"
	} else {
		return " not null"
	}
}

func (r *Oracle) ModifyUnsigned(_ schema.Blueprint, _ schema.ColumnDefinition) string {
	// Oracle doesn't support unsigned integers, so this is a no-op
	return ""
}

func (r *Oracle) TypeBigInteger(_ schema.ColumnDefinition) string {
	return "number(20)"
}

func (r *Oracle) TypeBoolean(_ schema.ColumnDefinition) string {
	return "number(1)"
}

func (r *Oracle) TypeChar(column schema.ColumnDefinition) string {
	return fmt.Sprintf("char(%d)", column.GetLength())
}

func (r *Oracle) TypeDate(_ schema.ColumnDefinition) string {
	return "date"
}

func (r *Oracle) TypeDateTime(column schema.ColumnDefinition) string {
	current := "CURRENT_TIMESTAMP"
	precision := column.GetPrecision()
	if precision > 0 {
		current = fmt.Sprintf("CURRENT_TIMESTAMP(%d)", precision)
	}
	if column.GetUseCurrent() {
		column.Default(Expression(current))
	}
	if column.GetUseCurrentOnUpdate() {
		column.OnUpdate(Expression(current))
	}

	if precision > 0 {
		return fmt.Sprintf("timestamp(%d)", precision)
	} else {
		return "timestamp"
	}
}

func (r *Oracle) TypeDateTimeTz(column schema.ColumnDefinition) string {
	return r.TypeDateTime(column)
}

func (r *Oracle) TypeDecimal(column schema.ColumnDefinition) string {
	return fmt.Sprintf("number(%d, %d)", column.GetTotal(), column.GetPlaces())
}

func (r *Oracle) TypeDouble(_ schema.ColumnDefinition) string {
	return "binary_double"
}

func (r *Oracle) TypeEnum(column schema.ColumnDefinition) string {
	return fmt.Sprintf(`varchar2(20) check (%s in (%s))`, column.GetName(), strings.Join(r.wrap.Quotes(cast.ToStringSlice(column.GetAllowed())), ", "))
}

func (r *Oracle) TypeFloat(column schema.ColumnDefinition) string {
	// Oracle BINARY_FLOAT doesn't support precision parameter
	return "binary_float"
}

func (r *Oracle) TypeGeometry(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypeGeometryCollection(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypeInteger(_ schema.ColumnDefinition) string {
	return "number(10)"
}

func (r *Oracle) TypeLineString(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypeJson(_ schema.ColumnDefinition) string {
	return "clob"
}

func (r *Oracle) TypeJsonb(_ schema.ColumnDefinition) string {
	return "clob"
}

func (r *Oracle) TypeLongText(_ schema.ColumnDefinition) string {
	return "clob"
}

func (r *Oracle) TypeMediumInteger(_ schema.ColumnDefinition) string {
	return "number(7)"
}

func (r *Oracle) TypeMediumText(_ schema.ColumnDefinition) string {
	return "clob"
}

func (r *Oracle) TypeMultiLineString(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypeMultiPoint(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypeMultiPolygon(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypePoint(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypePolygon(column schema.ColumnDefinition) string {
	return "sdo_geometry"
}

func (r *Oracle) TypeSmallInteger(_ schema.ColumnDefinition) string {
	return "number(5)"
}

func (r *Oracle) TypeString(column schema.ColumnDefinition) string {
	length := column.GetLength()
	if length > 0 {
		return fmt.Sprintf("varchar2(%d)", length)
	}

	return "varchar2(255)"
}

func (r *Oracle) TypeText(_ schema.ColumnDefinition) string {
	return "clob"
}

func (r *Oracle) TypeTime(column schema.ColumnDefinition) string {
	if column.GetPrecision() > 0 {
		return fmt.Sprintf("timestamp(%d)", column.GetPrecision())
	} else {
		return "timestamp"
	}
}

func (r *Oracle) TypeTimeTz(column schema.ColumnDefinition) string {
	return r.TypeTime(column)
}

func (r *Oracle) TypeTimestamp(column schema.ColumnDefinition) string {
	current := "CURRENT_TIMESTAMP"
	precision := column.GetPrecision()
	if precision > 0 {
		current = fmt.Sprintf("CURRENT_TIMESTAMP(%d)", precision)
	}
	if column.GetUseCurrent() {
		column.Default(Expression(current))
	}
	if column.GetUseCurrentOnUpdate() {
		column.OnUpdate(Expression(current))
	}

	if precision > 0 {
		return fmt.Sprintf("timestamp(%d)", precision)
	} else {
		return "timestamp"
	}
}

func (r *Oracle) TypeTimestampTz(column schema.ColumnDefinition) string {
	return r.TypeTimestamp(column)
}

func (r *Oracle) TypeTinyInteger(_ schema.ColumnDefinition) string {
	return "number(3)"
}

func (r *Oracle) TypeTinyText(_ schema.ColumnDefinition) string {
	return "varchar2(4000)"
}

func (r *Oracle) compileKey(blueprint schema.Blueprint, command *schema.Command, ttype string) (string, error) {
	table, err := r.wrap.Table(blueprint.GetTableName())
	if err != nil {
		return "", err
	}
	index, err := r.wrap.Column(command.Index)
	if err != nil {
		return "", err
	}
	columns, err := r.wrap.Columnize(command.Columns)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("create %s index %s on %s(%s)",
		ttype,
		index,
		table,
		columns), nil
}

func (r *Oracle) getColumns(blueprint schema.Blueprint) ([]string, error) {
	var columns []string
	for _, column := range blueprint.GetAddedColumns() {
		col, err := r.getColumn(blueprint, column)
		if err != nil {
			return nil, err
		}
		columns = append(columns, col)
	}

	return columns, nil
}

func (r *Oracle) getColumn(blueprint schema.Blueprint, column schema.ColumnDefinition) (string, error) {
	col, err := r.wrap.Column(column.GetName())
	if err != nil {
		return "", err
	}
	sql := fmt.Sprintf("%s %s", col, getType(r, column))

	for _, modifier := range r.modifiers {
		sql += modifier(blueprint, column)
	}

	return sql, nil
}
