package processors

import (
	"strings"

	"github.com/spf13/cast"

	"github.com/dracory/neat/contracts/database/schema"
)

type Oracle struct {
}

func NewOracle() Oracle {
	return Oracle{}
}

func (r Oracle) ProcessColumns(dbColumns []schema.DBColumn) []schema.Column {
	columns := make([]schema.Column, 0)
	for _, dbColumn := range dbColumns {
		var nullable bool
		if dbColumn.Nullable == "Y" {
			nullable = true
		}
		var autoIncrement bool
		// Oracle uses GENERATED BY DEFAULT AS IDENTITY
		if strings.Contains(dbColumn.Type, "identity") {
			autoIncrement = true
		}

		// Handle NULL comment - Oracle returns NULL for non-text columns
		var comment string
		if dbColumn.Comment != nil {
			comment = *dbColumn.Comment
		}

		// If Default is a pointer, dereference it safely
		defaultStr := cast.ToString(dbColumn.Default)
		columns = append(columns, schema.Column{
			Autoincrement: autoIncrement,
			Comment:       comment,
			Default:       defaultStr,
			Name:          dbColumn.Name,
			Nullable:      nullable,
			Type:          dbColumn.Type,
			TypeName:      dbColumn.TypeName,
		})
	}

	return columns
}

func (r Oracle) ProcessForeignKeys(dbForeignKeys []schema.DBForeignKey) []schema.ForeignKey {
	foreignKeys := make([]schema.ForeignKey, 0)
	for _, dbForeignKey := range dbForeignKeys {
		foreignKeys = append(foreignKeys, schema.ForeignKey{
			Name:           dbForeignKey.Name,
			Columns:        strings.Split(dbForeignKey.Columns, ","),
			ForeignSchema:  dbForeignKey.ForeignSchema,
			ForeignTable:   dbForeignKey.ForeignTable,
			ForeignColumns: strings.Split(dbForeignKey.ForeignColumns, ","),
			OnUpdate:       strings.ToLower(dbForeignKey.OnUpdate),
			OnDelete:       strings.ToLower(dbForeignKey.OnDelete),
		})
	}

	return foreignKeys
}

func (r Oracle) ProcessIndexes(dbIndexes []schema.DBIndex) []schema.Index {
	indexes := make([]schema.Index, 0)
	for _, dbIndex := range dbIndexes {
		name := strings.ToLower(dbIndex.Name)
		indexes = append(indexes, schema.Index{
			Columns: strings.Split(dbIndex.Columns, ","),
			Name:    name,
			Type:    strings.ToLower(dbIndex.Type),
			Primary: name == "primary",
			Unique:  dbIndex.Type == "UNIQUE",
		})
	}

	return indexes
}

func (r Oracle) ProcessTables(dbTables []schema.Table) []schema.Table {
	return dbTables
}
