package processors

import (
	"strings"

	"github.com/dracory/neat/contracts/database/schema"
)

type Oracle struct {
}

func NewOracle() Oracle {
	return Oracle{}
}

func (r Oracle) ProcessColumns(dbColumns []schema.DBColumn) []schema.Column {
	columns := make([]schema.Column, 0)
	for _, dbColumn := range dbColumns {
		var nullable bool
		// Oracle returns 'Y' for nullable, 'N' for NOT NULL
		if dbColumn.Nullable == "Y" {
			nullable = true
		}
		var autoIncrement bool
		// Oracle uses GENERATED BY DEFAULT AS IDENTITY
		// Check in TypeName since Type might not contain the full definition
		// Also check the Autoincrement field from the query if populated
		if dbColumn.Autoincrement || strings.Contains(dbColumn.TypeName, "identity") || strings.Contains(dbColumn.Type, "identity") {
			autoIncrement = true
		}

		// Handle NULL collation and comment - Oracle returns NULL for non-text columns
		var collation, comment string
		if dbColumn.Collation != nil {
			collation = *dbColumn.Collation
		}
		if dbColumn.Comment != nil {
			comment = *dbColumn.Comment
		}

		// If Default is a pointer, dereference it safely
		var defaultStr string
		if dbColumn.Default != nil {
			defaultStr = *dbColumn.Default
			// Oracle returns default values with quotes, strip them
			// e.g., "'hello'" becomes "hello"
			defaultStr = strings.TrimSpace(defaultStr)
			if len(defaultStr) >= 2 && strings.HasPrefix(defaultStr, "'") && strings.HasSuffix(defaultStr, "'") {
				defaultStr = defaultStr[1 : len(defaultStr)-1]
			}
		}
		columns = append(columns, schema.Column{
			Autoincrement: autoIncrement,
			Collation:     collation,
			Comment:       comment,
			Default:       defaultStr,
			Name:          strings.ToLower(dbColumn.Name),
			Nullable:      nullable,
			Type:          dbColumn.Type,
			TypeName:      dbColumn.TypeName,
		})
	}

	return columns
}

func (r Oracle) ProcessForeignKeys(dbForeignKeys []schema.DBForeignKey) []schema.ForeignKey {
	foreignKeys := make([]schema.ForeignKey, 0)
	for _, dbForeignKey := range dbForeignKeys {
		foreignKeys = append(foreignKeys, schema.ForeignKey{
			Name:           dbForeignKey.Name,
			Columns:        strings.Split(dbForeignKey.Columns, ","),
			ForeignSchema:  dbForeignKey.ForeignSchema,
			ForeignTable:   dbForeignKey.ForeignTable,
			ForeignColumns: strings.Split(dbForeignKey.ForeignColumns, ","),
			OnUpdate:       strings.ToLower(dbForeignKey.OnUpdate),
			OnDelete:       strings.ToLower(dbForeignKey.OnDelete),
		})
	}

	return foreignKeys
}

func (r Oracle) ProcessIndexes(dbIndexes []schema.DBIndex) []schema.Index {
	indexes := make([]schema.Index, 0)
	for _, dbIndex := range dbIndexes {
		name := strings.ToLower(dbIndex.Name)
		columns := strings.Split(dbIndex.Columns, ",")
		// Convert column names to lowercase
		for i, col := range columns {
			columns[i] = strings.ToLower(strings.TrimSpace(col))
		}
		indexes = append(indexes, schema.Index{
			Columns: columns,
			Name:    name,
			Type:    strings.ToLower(dbIndex.Type),
			Primary: dbIndex.Primary,
			Unique:  dbIndex.Type == "UNIQUE",
		})
	}

	return indexes
}

func (r Oracle) ProcessTables(dbTables []schema.Table) []schema.Table {
	for i := range dbTables {
		dbTables[i].Name = strings.ToLower(dbTables[i].Name)
	}
	return dbTables
}
